### ISSUE TITLE
Maybe setup variables only if they're needed?

### ISSUE THREAD

**Issue by LeeGrissom** [kaijuking/pythonlearning#1]
Is it a good habit to get into to perform work on an "as-needed" basis? For example, in the code snippet below, I moved the #setup variables section down a little so that if we need to early return, we don't bother setting any variables since they wouldn't be used.
```
def roman_numerals_v1(x):
    
    # get rid of whitespaces
    x = get_rid_of_whitespaces(x)

    # return 0 if empty string
    if len(x) == 0:
        return 0

    # setup variables
    total = 0
    tmp_list = []
    roman_val = get_roman_values()

```

**Comment by kaijuking** [comment]
Updated code per feedback. Thank you Lee!
